version: '3.7'
services:
  vue:
    container_name: perforator-front
    image: 'perforator-front:latest'
    build: .
    ports:
      - '8080:443'
    networks:
      - default

networks:
  default:
    external: true
    name: sklyarv