export const types = {
  SET_AUTH: "SET_AUTH",
  CLEAR_AUTH_ERRORS: "CLEAR_AUTH_ERRORS",
  SET_PEERS: "SET_PEERS",
  SET_TEAM: "SET_TEAM",
  SET_TEAM_WITHOUT_REVIEW: "SET_TEAM_WITHOUT_REVIEW",
  SET_TEAM_WITH_REVIEW: "SET_TEAM_WITH_REVIEW",
  SET_TEAM_APPROVE: "SET_TEAM_APPROVE",
  SET_PEERS_ALL: "SET_PEERS_ALL",
  ADD_MY_PEER: "ADD_MY_PEER",
  ADD_PEER_All: "ADD_PEER_All",
  SET_SELFREVIEW: "SET_SELFREVIEW",
};
